# -*- coding: utf-8 -*-
"""4/14 Updated Code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PouC7C4AimCUXZx_YEHg9KrbgBvxSlwZ
"""

import requests
import re
from typing import Any, Dict, List

API_URL = "https://chat.illinois.edu/api/chat-api/chat"
API_KEY = "uc_62829d731c2344df848201c06ea0ebf0"
COURSE_NAME = "ChatbotBLS2"
MODEL_NAME = "llama4:16x17b"

FALLBACK = "I don't know based on the provided documents."


SYSTEM_PROMPT_ANSWER = """You are an neutral informational assistant for the University of Illinois Bachelor of Liberal Studies (BLS) program.

Your goal is to provide clear, accurate, and EASY-TO-UNDERSTAND answers for prospective students.

- Always start with a short, simple explanation.
- Use a professional, matter-of-fact tone. Do NOT be "friendly" or welcoming.
- Use plain English (no jargon).
- Be concise but helpful.
- Format the response for readability.
- After the opening explanation, split longer answers into short paragraphs or bullets when helpful.
- Do NOT put everything in one long paragraph.
- If the answer has multiple features or distinct points, ALWAYS use bullet points.
- Keep each paragraph short, usually 1–3 sentences.
- Terminology: If referring to standard students or programs, use the term "on-campus." NEVER use the word "traditional."
- Neutrality: Do NOT mention any specific target groups, race, gender, cultures, or demographics.
- Do NOT include citations, file names, or raw document text.
- If unsure, say exactly: "I don't know based on the provided documents."

ADDITIONAL FACT RULES:
- Only answer using information clearly supported by the retrieved materials.
- Do NOT guess, infer, estimate, or fill in missing details.
- Do NOT combine separate pieces of information unless the connection is explicitly supported.
- Do NOT make claims about transfer credits, course flexibility, pacing, program format, admissions, cost, or requirements unless those details are clearly stated.
- If the retrieved materials are ambiguous, incomplete, or conflicting, say exactly: "I don't know based on the provided documents."
- Prefer a shorter answer over a broader answer if broadness could introduce unsupported claims.
- Do not mention where the information came from.
"""


SYSTEM_PROMPT_VERIFY = """You are a strict factual verifier and final editor for answers about the University of Illinois Bachelor of Liberal Studies (BLS) program.

You will receive:
- the user question
- the retrieved evidence
- a draft answer

Your task:
1. Compare the draft answer against the retrieved evidence.
2. Delete or rewrite any statement that is not clearly supported by the retrieved evidence.
3. Keep only claims that are directly grounded in the evidence.
4. If the answer is mostly unsupported, return exactly:
I don't know based on the provided documents.

HARD RULES:
- Do NOT rely on outside knowledge.
- Do NOT preserve claims that are inferred, speculative, overly broad, or too confident.
- Do NOT add any new facts.
- If a detail is not clearly supported by the retrieved evidence, remove it.
- Be especially strict about transfer credit, flexibility, course choice, self-paced learning, synchronous format, admission, cost, timing, and program structure.
- Remove any source labels, source numbers, citation placeholders, or reference footers.
- Remove markdown artifacts such as **, ---, or leftover formatting symbols.
- Fix stray punctuation such as ;:, ;., ,;, or repeated punctuation marks.

STYLE RULES:
1. DELETE every single file name.
2. Replace "traditional" with "on-campus" if it appears.
3. DELETE every page number reference.
4. DELETE all mention of "documents," "sources," or "cites," EXCEPT for the exact fallback sentence.
5. Strip out friendly filler.
6. Ensure the response is a neutral statement of fact.
7. Keep it concise.

FORMAT RULES (VERY IMPORTANT):
8. PRESERVE the original structure if it is already clear (paragraphs or bullets).
9. DO NOT collapse bullet points into a paragraph.
10. If the answer contains multiple distinct points, format them as bullet points.
11. Use line breaks between sections when helpful.
12. Each bullet should be one short sentence or phrase.
13. NEVER return a single long paragraph if the content can be structured.

Return ONLY the final cleaned answer text.
"""


def post_api(payload: Dict[str, Any]) -> Dict[str, Any]:
    try:
        response = requests.post(API_URL, json=payload, timeout=60)
        response.raise_for_status()
        return response.json()
    except requests.RequestException as e:
        return {"error": str(e)}
    except ValueError:
        return {"error": "Invalid JSON response"}


def call_chat(
    messages: List[Dict[str, str]],
    temperature: float = 0.0,
    retrieval_only: bool = False
) -> Dict[str, Any]:
    payload = {
        "model": MODEL_NAME,
        "messages": messages,
        "api_key": API_KEY,
        "course_name": COURSE_NAME,
        "stream": False,
        "temperature": temperature,
        "retrieval_only": retrieval_only
    }
    return post_api(payload)


def extract_answer(data: Dict[str, Any]) -> str:
    if "error" in data:
        return f"Error: {data['error']}"

    if "message" in data and isinstance(data["message"], str):
        return data["message"]

    if "response" in data and isinstance(data["response"], str):
        return data["response"]

    if "choices" in data and isinstance(data["choices"], list) and data["choices"]:
        try:
            return data["choices"][0]["message"]["content"]
        except (KeyError, TypeError, IndexError):
            pass

    return "Error: Unexpected response format."


def extract_evidence(data: Dict[str, Any]) -> str:
    candidate_fields = [
        "retrieved_chunks",
        "sources",
        "documents",
        "context",
        "citations",
        "results"
    ]

    chunks: List[str] = []

    def collect_from_item(item: Any) -> None:
        if isinstance(item, str):
            stripped = item.strip()
            if stripped:
                chunks.append(stripped)

        elif isinstance(item, list):
            for sub_item in item:
                collect_from_item(sub_item)

        elif isinstance(item, dict):
            for key in [
                "text",
                "content",
                "chunk",
                "snippet",
                "body",
                "page_content",
                "pageContent"
            ]:
                if key in item and item[key]:
                    value = str(item[key]).strip()
                    if value:
                        chunks.append(value)

            for value in item.values():
                if isinstance(value, (list, dict)):
                    collect_from_item(value)

    for field in candidate_fields:
        if field in data:
            collect_from_item(data[field])

    # deduplicate while preserving order
    unique_chunks = list(dict.fromkeys(chunks))
    return "\n\n".join(unique_chunks)


def clean_text(text: str) -> str:
    if not text:
        return ""

    cleaned = text

    # Remove whole Citations / Sources section at the end
    cleaned = re.sub(
        r'(?is)\n\s*(citations?|sources?)\s*:\s*\n(?:\s*[\[\(]?\d+[\]\)]?\.?\s*\n?|\s*[-*]?\s*.*\n?)*$',
        '',
        cleaned
    )

    # Remove one-line source/citation labels
    cleaned = re.sub(r'(?im)^\s*(citations?|sources?)\s*:.*$', '', cleaned)

    # Remove standalone numbered citation lines
    cleaned = re.sub(r'(?im)^\s*\d+\.\s*$', '', cleaned)

    # Remove filenames with optional page refs
    cleaned = re.sub(
        r'[\w.\- /()]+\.(pdf|rtf|docx|txt|pptx)(,\s*(p\.|page)\s*\d+)?',
        '',
        cleaned,
        flags=re.IGNORECASE
    )

    # Remove standalone page refs
    cleaned = re.sub(r'\b(p\.|page)\s*\d+\b', '', cleaned, flags=re.IGNORECASE)

    # Remove markdown separators / headings / stars
    cleaned = re.sub(r'(?m)^\s*---+\s*$', '', cleaned)
    cleaned = re.sub(r'(?m)^\s*#{1,6}\s*', '', cleaned)
    cleaned = cleaned.replace("**", "")
    cleaned = cleaned.replace("*", "")

    # Normalize bullets
    cleaned = re.sub(r'(?m)^\s*[-•]\s*', '- ', cleaned)

    # Normalize spacing
    cleaned = re.sub(r'\s+([.,;:!?])', r'\1', cleaned)
    cleaned = re.sub(r'[ \t]{2,}', ' ', cleaned)

    # Fix stray punctuation combinations aggressively
    cleaned = re.sub(r'\s*;\s*\.', '.', cleaned)
    cleaned = re.sub(r'\s*,\s*\.', '.', cleaned)
    cleaned = re.sub(r'\s*:\s*\.', '.', cleaned)
    cleaned = re.sub(r';,', ',', cleaned)
    cleaned = re.sub(r',;', ';', cleaned)
    cleaned = re.sub(r'\.{2,}', '.', cleaned)

    # Remove semicolon/comma/colon before line end or paragraph end
    cleaned = re.sub(r'[;,:]+(?=\s*(\n|$))', '', cleaned)

    # Fix punctuation before closing quotes / parentheses
    cleaned = re.sub(r';(?=[\'")\]])', '', cleaned)
    cleaned = re.sub(r',(?=[\'")\]])', '', cleaned)
    cleaned = re.sub(r':(?=[\'")\]])', '', cleaned)

    # If punctuation is duplicated strangely, keep the stronger ending mark
    cleaned = re.sub(r'([.!?])[;,:]+', r'\1', cleaned)
    cleaned = re.sub(r'[;,:]+([.!?])', r'\1', cleaned)

    # Normalize excessive blank lines
    cleaned = re.sub(r'\n{3,}', '\n\n', cleaned)

    # Strip trailing punctuation junk from each line
    cleaned = "\n".join(line.rstrip(" ;,:") for line in cleaned.splitlines())

    return cleaned.strip()


def enforce_format(text: str) -> str:
    text = text.strip()
    if not text:
        return ""

    # Keep if already clearly structured
    if "\n- " in text or text.startswith("- ") or "\n• " in text or text.startswith("• "):
        return text

    paragraphs = [p.strip() for p in text.split("\n\n") if p.strip()]
    if len(paragraphs) > 1:
        return "\n\n".join(paragraphs)

    # If multiple sentences and no structure, convert to bullets
    sentences = re.split(r'(?<=[.!?])\s+', text)
    sentences = [s.strip() for s in sentences if s.strip()]

    if len(sentences) >= 3:
        intro = sentences[0]
        bullets = sentences[1:]
        return intro + "\n\n" + "\n".join(f"- {s}" for s in bullets)

    return text


def get_retrieved_evidence(user_query: str) -> tuple[str, Dict[str, Any]]:
    retrieval_data = call_chat(
        [{"role": "user", "content": user_query}],
        temperature=0.0,
        retrieval_only=True
    )

    evidence = extract_evidence(retrieval_data)
    return evidence, retrieval_data


def ask_chatbot(user_query: str, debug: bool = False) -> str:
    evidence, retrieval_data = get_retrieved_evidence(user_query)

    if debug:
        print("\n[DEBUG] retrieval_data keys:", list(retrieval_data.keys()))
        if evidence:
            print("\n[DEBUG] extracted evidence from retrieval_only:\n", evidence[:2000])

    # If retrieval_only does not return usable evidence, fall back to normal call
    if not evidence:
        first_data = call_chat(
            [
                {"role": "system", "content": SYSTEM_PROMPT_ANSWER},
                {"role": "user", "content": user_query}
            ],
            temperature=0.0,
            retrieval_only=False
        )

        raw_answer = extract_answer(first_data)
        evidence = extract_evidence(first_data)

        if debug:
            print("\n[DEBUG] first_data keys:", list(first_data.keys()))
            if evidence:
                print("\n[DEBUG] extracted evidence from normal call:\n", evidence[:2000])
            print("\n[DEBUG] raw_answer:\n", raw_answer[:2000])

        if raw_answer.startswith("Error"):
            return raw_answer

    else:
        answer_input = f"""User question:
{user_query}

Retrieved evidence:
{evidence}

Answer using only the retrieved evidence above.
If the evidence is insufficient, say exactly:
{FALLBACK}
"""

        first_data = call_chat(
            [
                {"role": "system", "content": SYSTEM_PROMPT_ANSWER},
                {"role": "user", "content": answer_input}
            ],
            temperature=0.0,
            retrieval_only=False
        )

        raw_answer = extract_answer(first_data)

        if debug:
            print("\n[DEBUG] raw_answer from evidence-fed agent 1:\n", raw_answer[:2000])

        if raw_answer.startswith("Error"):
            return raw_answer

    if not evidence:
        evidence = "[No retrieved evidence was available from the API response.]"

    verify_input = f"""User question:
{user_query}

Retrieved evidence:
{evidence}

Draft answer:
{raw_answer}
"""

    second_data = call_chat(
        [
            {"role": "system", "content": SYSTEM_PROMPT_VERIFY},
            {"role": "user", "content": verify_input}
        ],
        temperature=0.0,
        retrieval_only=False
    )

    final_answer = extract_answer(second_data)

    if debug:
        print("\n[DEBUG] final_answer before cleaning:\n", final_answer[:2000])

    if final_answer.startswith("Error"):
        return final_answer

    cleaned = clean_text(final_answer)
    formatted = enforce_format(cleaned)

    return formatted if formatted else FALLBACK


if __name__ == "__main__":
    print("\nUIUC BLS Chatbot")
    print("Type 'exit' to quit.\n")

    DEBUG_MODE = False

    while True:
        user_input = input("You: ").strip()

        if user_input.lower() == "exit":
            print("Goodbye!")
            break

        if not user_input:
            print(f"\nBot: {FALLBACK}\n")
            continue

        answer = ask_chatbot(user_input, debug=DEBUG_MODE)
        print("\nBot:\n")
        print(answer)
        print()

"""####qwen3:32b
####qwen2.5-vl:72b
"gemini-2.5-pro-exp-03-25"

"""