# -*- coding: utf-8 -*-
"""Updated Codebook

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z6fkNlOdZaRBBVXhB2nDbOFsbp9V2WTe

Step 1 — Install libraries
"""

pip install -q langchain langchain-community langchain-openai faiss-cpu pypdf tiktoken

"""Step 2 — Load PDFs and check if able to extract text"""

import os
from google.colab import files

# Create the documents_folder if it doesn't exist
os.makedirs("documents_folder", exist_ok=True)

uploaded = files.upload()

import shutil

for file in uploaded.keys():
    shutil.move(file, f"documents_folder/{file}")

import os
os.makedirs("documents_folder", exist_ok=True)
os.listdir()

#from langchain_community.document_loaders import PyPDFLoader

#loader = PyPDFLoader("BLS Overview-OperationsDiscussion-5.15.2025.pdf")
#pages = loader.load()

#print(len(pages))
#print(pages[0].page_content[:800])

from langchain_community.document_loaders import DirectoryLoader
from langchain_community.document_loaders import PyPDFLoader

loader = DirectoryLoader(
    "documents_folder/",
    glob="**/*.pdf",
    loader_cls=PyPDFLoader,
    show_progress=True
)

documents = loader.load()

print("Total pages loaded:", len(documents))
print(documents[0].page_content[:500])

"""Step 3 — Chunk the text"""

from langchain_text_splitters import RecursiveCharacterTextSplitter

splitter = RecursiveCharacterTextSplitter(
    chunk_size=600,
    chunk_overlap=120
)

docs = splitter.split_documents(documents)
print("chunks:", len(docs))
print(docs[0].page_content[:300])

"""Step 4 — Create embeddings and build a vector DB (FAISS)"""

from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS

embeddings = HuggingFaceEmbeddings(model_name="BAAI/bge-base-en-v1.5")

vectorstore = FAISS.from_documents(docs, embeddings)
vectorstore.save_local("bls_faiss_index")

print("Index built successfully!")

"""Step 5 — Load vector DB and retrieve chunks"""

vectorstore = FAISS.load_local(
    "bls_faiss_index",
    embeddings,
    allow_dangerous_deserialization=True
)

retriever = vectorstore.as_retriever(search_kwargs={"k": 4})

question = "What is the Bachelor of Liberal Studies (BLS) degree?"
docs = retriever.invoke(question)

for i, d in enumerate(docs):
    print("------", i, "------")
    print(d.page_content[:500])
    print("\n")

"""**Build the two-agent system**

Agent 1 — Answer Agent (must be grounded)

Step A — Install local LLM dependencies (Colab)
"""

pip -q install transformers accelerate bitsandbytes

"""Step B — Load model + build a local text-generation pipeline"""

import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline

MODEL_NAME = "Qwen/Qwen2.5-1.5B-Instruct"

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    torch_dtype=torch.float16,
    device_map="auto"
)

gen = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    max_new_tokens=120,
    do_sample=False,
    temperature=0.0,
    return_full_text=False
)

"""Step C — Create a simple function to call the local LLM"""

def call_llm(prompt: str) -> str:
    return gen(prompt)[0]["generated_text"].strip()

"""Step D — Build Answer Agent prompt (grounded)"""

def answer_agent(context: str, question: str) -> str:
    prompt = f"""
Extract the answer from the CONTEXT. Do NOT add any information.

Return in this exact JSON format:
{{
  "answer": "<1-3 sentences>",
  "evidence": ["<exact quote 1>", "<exact quote 2>"]
}}

QUESTION: {question}

CONTEXT:
{context}

JSON:
""".strip()
    return call_llm(prompt)

"""Step E — Build Verifier Agent prompt (strict)"""

def verify_agent(context: str, answer: str) -> str:
    prompt = f"""
You are a strict verifier.

Check whether the answer is fully supported by the context.
Return exactly one of the following:

VERIFIED

or

REJECTED: <short reason>

Context:
{context}

Answer:
{answer}

Verdict:
""".strip()
    return call_llm(prompt)

"""Step F — Put it together with your retriever"""

docs = retriever.invoke(question)

def retrieve_context(question: str) -> str:
    docs = retriever.invoke(question)
    return "\n\n".join([d.page_content for d in docs])

def two_agent_chat(question: str) -> str:
    context = retrieve_context(question)
    ans = answer_agent(context, question)
    verdict = verify_agent(context, ans)

    if verdict.startswith("VERIFIED"):
        return ans
    else:
        return "I couldn’t verify that answer from the official documents. Please contact the program directly."

print(two_agent_chat("What concentrations are available?"))

"""Debug mode"""

def two_agent_chat_debug(question: str):
    context = retrieve_context(question)
    draft = answer_agent(context, question)
    verdict = verify_agent(context, draft)

    print("=== QUESTION ===")
    print(question)
    print("\n=== CONTEXT (first 800 chars) ===")
    print(context[:800])
    print("\n=== DRAFT ANSWER ===")
    print(repr(draft))         # repr shows if it's truly empty
    print("\n=== RAW VERDICT ===")
    print(repr(verdict))

    if verdict.strip().startswith("VERIFIED") and draft.strip():
        return draft
    else:
        return "I couldn’t verify that answer from the official documents. Please contact the program directly."

print(two_agent_chat_debug("What concentrations are available?"))